import 'package:flutter/foundation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/user_model.dart';
import '../models/motorcycle_model.dart';
import '../models/monitoring_model.dart';

class TeknisiProvider extends ChangeNotifier {
  final SupabaseClient _supabase = Supabase.instance.client;

  List<UserModel> _users = [];
  Map<String, List<MotorcycleModel>> _userMotorcycles = {};
  List<MonitoringModel> _monitoringList = [];
  bool _isLoading = false;
  String? _errorMessage;

  List<UserModel> get users => _users;
  Map<String, List<MotorcycleModel>> get userMotorcycles => _userMotorcycles;
  List<MonitoringModel> get monitoringList => _monitoringList;
  bool get isLoading => _isLoading;
  String? get errorMessage => _errorMessage;

  int get totalUsers => _users.length;
  int get totalMotorcycles =>
      _userMotorcycles.values.fold(0, (sum, list) => sum + list.length);

  /// Fetch all users with role 'user' and their motorcycles
  Future<void> fetchAllUsersWithMotorcycles() async {
    _setLoading(true);
    _errorMessage = null;
    try {
      // Fetch users with role 'user'
      final usersResponse = await _supabase
          .from('users')
          .select()
          .eq('role', 'user')
          .order('name', ascending: true);

      _users = (usersResponse as List)
          .map((json) => UserModel.fromJson(json))
          .toList();

      // Fetch all motorcycles for these users
      final userIds = _users.map((u) => u.id).toList();
      if (userIds.isNotEmpty) {
        final motorcyclesResponse = await _supabase
            .from('motorcycles')
            .select()
            .inFilter('user_id', userIds);

        final allMotorcycles = (motorcyclesResponse as List)
            .map((json) => MotorcycleModel.fromJson(json))
            .toList();

        // Group motorcycles by user_id
        _userMotorcycles = {};
        for (var motorcycle in allMotorcycles) {
          _userMotorcycles
              .putIfAbsent(motorcycle.userId, () => [])
              .add(motorcycle);
        }
      }

      notifyListeners();
    } catch (e) {
      _errorMessage = 'Gagal memuat data user: $e';
      debugPrint('TeknisiProvider fetchAllUsersWithMotorcycles error: $e');
    } finally {
      _setLoading(false);
    }
  }

  /// Fetch monitoring records for a specific user
  Future<void> fetchMonitoringForUser(String userId) async {
    _setLoading(true);
    _errorMessage = null;
    try {
      final response = await _supabase
          .from('monitoring')
          .select('*, motorcycles(brand, model)')
          .eq('user_id', userId)
          .order('created_at', ascending: false);

      _monitoringList = (response as List)
          .map((json) => MonitoringModel.fromJson(json))
          .toList();

      notifyListeners();
    } catch (e) {
      _errorMessage = 'Gagal memuat data monitoring: $e';
      debugPrint('TeknisiProvider fetchMonitoringForUser error: $e');
    } finally {
      _setLoading(false);
    }
  }

  /// Add a new monitoring record
  Future<bool> addMonitoring({
    required String userId,
    String? motorcycleId,
    String? catatan,
    String? rekomendasi,
    required String status,
  }) async {
    _setLoading(true);
    _errorMessage = null;
    try {
      final teknisiId = _supabase.auth.currentUser?.id;
      if (teknisiId == null) throw 'Tidak terautentikasi';

      final monitoring = MonitoringModel(
        id: '', // Will be generated by DB
        userId: userId,
        teknisiId: teknisiId,
        motorcycleId: motorcycleId,
        catatan: catatan,
        rekomendasi: rekomendasi,
        status: status,
      );

      await _supabase.from('monitoring').insert(monitoring.toInsertJson());

      // Refresh monitoring list
      await fetchMonitoringForUser(userId);
      return true;
    } catch (e) {
      _errorMessage = 'Gagal menambah monitoring: $e';
      debugPrint('TeknisiProvider addMonitoring error: $e');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  /// Delete a monitoring record
  Future<bool> deleteMonitoring(String monitoringId, String userId) async {
    _setLoading(true);
    _errorMessage = null;
    try {
      await _supabase.from('monitoring').delete().eq('id', monitoringId);
      await fetchMonitoringForUser(userId);
      return true;
    } catch (e) {
      _errorMessage = 'Gagal menghapus monitoring: $e';
      debugPrint('TeknisiProvider deleteMonitoring error: $e');
      return false;
    } finally {
      _setLoading(false);
    }
  }

  /// Get motorcycles for a specific user
  List<MotorcycleModel> getMotorcyclesForUser(String userId) {
    return _userMotorcycles[userId] ?? [];
  }

  void _setLoading(bool value) {
    _isLoading = value;
    notifyListeners();
  }
}
